version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../data/nginx/conf.d:/etc/nginx/conf.d
      - ../data/nginx/cert:/etc/nginx/cert
      - ../data/nginx/log:/var/log/nginx
    container_name: root_nginx
