version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    container_name: mysql_ning
    volumes:
      - "../data/mysql/data:/var/lib/mysql" # 挂载数据目录
      - "../data/mysql/config:/etc/mysql/conf.d" # 挂载配置文件目录
    environment:
      MYSQL_ROOT_PASSWORD: root #root@root
      MYSQL_DATA_BASE: pass
