version: '3'
services:
  pgsql:
    container_name: pgsql_ning
    restart: always
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - "$PWD/.pgdata/data:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_PASSWORD: root #postgres@root
      PGDATA: /var/lib/postgresql/data/pgdata

