version: '3.8'
services:  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: china_ningning@outlook.com
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    ports:
      - "5050:80"