version: '3'
services:
  mongo:
    container_name: mongo_ning
    image: mongo
    ports:
      - 27017:27017
    volumes:
    - "../data/mongo/data/configdb:/data/configdb"
    - "../data/mongo/data/db:/data/db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    container_name: mongo_express_ning
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root