version: '3'
services:
   redis:
     image: redis:latest
     restart: "no"
     container_name: redis
     ports:
       - "6379:6379"
     volumes:
       - $HOME/.docker/redis/redis.conf:/etc/redis/redis.conf 
       - $HOME/.docker/redis/data:/data      
     command: redis-server /etc/redis/redis.conf 
     privileged: true